name: iOS PR Verification

on:
  pull_request:
    branches: [ master ]
    # TODO: remove this path selector when we have more integrated tests
    paths: 'iOS/**'

jobs:
  pr_verification:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: 'install all ruby dependencies (e.g: Fastlane)'
        run: bundle install
        
      - name: install Carthage
        run: brew install carthage
      
      - name: execute Fastlane
        run: bundle exec fastlane ios pull_request_verification